// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AnalyzeExistingWPRTrace():Promise<models.FixActionResult>;

export function CancelPendingReboot():Promise<models.FixActionResult>;

export function CancelWPRBootTrace():Promise<models.FixActionResult>;

export function ClearTraceData():Promise<models.FixActionResult>;

export function ExecuteQuickFix(arg1:string):Promise<models.FixActionResult>;

export function ExportAndOpenHTMLReport():Promise<string>;

export function ExportJSONReport():Promise<string>;

export function GenerateAndOpenGPOReport():Promise<models.GPOReportResult>;

export function GetAdvancedAutoruns():Promise<Array<models.AdvancedAutorunsItem>>;

export function GetHealthReport():Promise<models.HealthReport>;

export function OpenTraceFolder():Promise<string>;

export function OpenTraceInWPA():Promise<boolean>;

export function OpenWPTInstallGuide():Promise<void>;

export function StartWPRBootTrace(arg1:string):Promise<models.FixActionResult>;

export function StartWPRBootTraceWithReboot(arg1:string,arg2:boolean):Promise<models.FixActionResult>;

export function StopWPRBootTrace():Promise<models.FixActionResult>;

export function ToggleStartupApp(arg1:string,arg2:string,arg3:boolean):Promise<models.FixActionResult>;

export function ToggleWindowsUpdateHidden(arg1:string,arg2:boolean):Promise<models.FixActionResult>;
