// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExistingWPRTrace() {
  return window['go']['main']['App']['AnalyzeExistingWPRTrace']();
}

export function CancelPendingReboot() {
  return window['go']['main']['App']['CancelPendingReboot']();
}

export function CancelWPRBootTrace() {
  return window['go']['main']['App']['CancelWPRBootTrace']();
}

export function ClearTraceData() {
  return window['go']['main']['App']['ClearTraceData']();
}

export function ExecuteQuickFix(arg1) {
  return window['go']['main']['App']['ExecuteQuickFix'](arg1);
}

export function ExportAndOpenHTMLReport() {
  return window['go']['main']['App']['ExportAndOpenHTMLReport']();
}

export function ExportJSONReport() {
  return window['go']['main']['App']['ExportJSONReport']();
}

export function GenerateAndOpenGPOReport() {
  return window['go']['main']['App']['GenerateAndOpenGPOReport']();
}

export function GetAdvancedAutoruns() {
  return window['go']['main']['App']['GetAdvancedAutoruns']();
}

export function GetHealthReport() {
  return window['go']['main']['App']['GetHealthReport']();
}

export function OpenTraceFolder() {
  return window['go']['main']['App']['OpenTraceFolder']();
}

export function OpenTraceInWPA() {
  return window['go']['main']['App']['OpenTraceInWPA']();
}

export function OpenWPTInstallGuide() {
  return window['go']['main']['App']['OpenWPTInstallGuide']();
}

export function StartWPRBootTrace(arg1) {
  return window['go']['main']['App']['StartWPRBootTrace'](arg1);
}

export function StartWPRBootTraceWithReboot(arg1, arg2) {
  return window['go']['main']['App']['StartWPRBootTraceWithReboot'](arg1, arg2);
}

export function StopWPRBootTrace() {
  return window['go']['main']['App']['StopWPRBootTrace']();
}

export function ToggleStartupApp(arg1, arg2, arg3) {
  return window['go']['main']['App']['ToggleStartupApp'](arg1, arg2, arg3);
}

export function ToggleWindowsUpdateHidden(arg1, arg2) {
  return window['go']['main']['App']['ToggleWindowsUpdateHidden'](arg1, arg2);
}
